In [6]:
import numpy as np

In [10]:
ex3 = np.eye(4,4)
print(ex3)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [13]:
ex4 = np.ones((1,2))
print(ex4)

[[ 1.  1.]]


In [14]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x1 array
print(ex4.shape)

#which means we need to use two indexes to access an element
print()
print(ex4[0,1])

(1, 2)

1.0


In [19]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((3,3))
print(ex5)

[[ 0.2408798   0.68043851  0.38534936]
 [ 0.78702846  0.13903749  0.30804001]
 [ 0.59718175  0.62222942  0.2818017 ]]


In [20]:
# rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use array slicing to get a subrray of the first 2 rows x 2 columns

In [27]:
a_slice = an_array[:2, 1:3]
b_slice = np.array(a_slice)
b_slice[0,0] = 500
c_slice = np.array(an_array[:2, 1:3])
print(a_slice)
print(b_slice)
print(c_slice)

[[1000   13]
 [  22   23]]
[[500  13]
 [ 22  23]]
[[1000   13]
 [  22   23]]


When you modify a slice, you actually modify the underlying array.

In [22]:
print("Before:", an_array[0,1]) #inspect the element at 0,1
a_slice[0,0] = 1000 # a_slice[0,0] is the same piece of data as an_array[0,1]
print("After:", an_array[0,1])

Before: 12
After: 1000


# Use both integer indexing & slice indexing

#### We can use combinations of integer indexing and slice indexing to create different shaped matrices